# Generated by Django 3.2.7 on 2021-09-10 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sedan, Carbriolet, etc.', max_length=50, verbose_name='Car body style')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('companyOwner', models.CharField(blank=True, help_text='empty if the same as brand name', max_length=100, null=True)),
                ('creationDate', models.DateField(blank=True, help_text='the date when the brand was created', null=True)),
            ],
            options={
                'ordering': ['name', '-creationDate'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('bodyStyle', models.ManyToManyField(to='catalog.BodyStyle')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique car ID', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('plate', models.CharField(help_text='<a href="https://en.wikipedia.org/wiki/Vehicle_registration_plate">8 characters</a> in form AB1234BC', max_length=8, unique=True, verbose_name='Vehicle registration plate')),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On rent'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Car availability', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.car')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
