# Generated by Django 3.2.7 on 2021-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='carinstance',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
